      - run: # run tests
          name: test
          command: npm test
      - run: # run coverage report
          name: code-coverage
          command: jest --collectCoverage=true
      - store_artifacts: # special step to save test results as as artifact
          path: coverage
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results: # special step to upload test results for display in Test Summary
          path: test-results.xml
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
deployment:
  production: # just a label; label names are completely up to you
    branch: master
    heroku:
      appname: cardsforhumanityapp